/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AbstractTeeAuthenticator,
  AbstractTeeAuthenticatorInterface,
} from "../../contracts/AbstractTeeAuthenticator";

const _abi = [
  {
    inputs: [],
    name: "ECDSAInvalidSignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
    ],
    name: "ECDSAInvalidSignatureLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "ECDSAInvalidSignatureS",
    type: "error",
  },
  {
    inputs: [],
    name: "TeeIsNotSet",
    type: "error",
  },
  {
    inputs: [],
    name: "PK_LENGTH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "applicationId",
        type: "uint64",
      },
      {
        internalType: "bytes32",
        name: "prevStateRoot",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "newStateRoot",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "processedRequestId",
        type: "bytes32",
      },
      {
        internalType: "bytes[]",
        name: "events",
        type: "bytes[]",
      },
      {
        internalType: "string[]",
        name: "eventSubTypes",
        type: "string[]",
      },
      {
        components: [
          {
            internalType: "address payable",
            name: "receiver",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct Structs.WithdrawalRequest[]",
        name: "withdrawalRequests",
        type: "tuple[]",
      },
      {
        internalType: "uint256",
        name: "refundAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "applicationFee",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "checkSignature",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPubSecp521r1",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTeeSigner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class AbstractTeeAuthenticator__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractTeeAuthenticatorInterface {
    return new Interface(_abi) as AbstractTeeAuthenticatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AbstractTeeAuthenticator {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AbstractTeeAuthenticator;
  }
}
