/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAuthorityChecker,
  IAuthorityCheckerInterface,
} from "../../../contracts/interfaces/IAuthorityChecker";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "applicationId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "checkAuthorityIsAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAuthorityChecker__factory {
  static readonly abi = _abi;
  static createInterface(): IAuthorityCheckerInterface {
    return new Interface(_abi) as IAuthorityCheckerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAuthorityChecker {
    return new Contract(address, _abi, runner) as unknown as IAuthorityChecker;
  }
}
