/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDefaultAuthorityChecker,
  IDefaultAuthorityCheckerInterface,
} from "../../../contracts/interfaces/IDefaultAuthorityChecker";

const _abi = [
  {
    inputs: [],
    name: "AuthorityAlreadyPresent",
    type: "error",
  },
  {
    inputs: [],
    name: "AuthorityNotPresent",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "applicationId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "AddedAuthority",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "applicationId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "RemovedAuthority",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "applicationId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "addAllowedAuthority",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "applicationId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "checkAuthorityIsAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "applicationId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "authority",
        type: "address",
      },
    ],
    name: "removeAllowedAuthority",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDefaultAuthorityChecker__factory {
  static readonly abi = _abi;
  static createInterface(): IDefaultAuthorityCheckerInterface {
    return new Interface(_abi) as IDefaultAuthorityCheckerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDefaultAuthorityChecker {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDefaultAuthorityChecker;
  }
}
