/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INitroValidator,
  INitroValidatorInterface,
} from "../../../contracts/interfaces/INitroValidator";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "attestation",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "maxAge",
        type: "uint256",
      },
    ],
    name: "verifyAttestation",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INitroValidator__factory {
  static readonly abi = _abi;
  static createInterface(): INitroValidatorInterface {
    return new Interface(_abi) as INitroValidatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INitroValidator {
    return new Contract(address, _abi, runner) as unknown as INitroValidator;
  }
}
