/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAuthorityChecker } from "./IAuthorityChecker";
export type { INitroProver } from "./INitroProver";
export type { ITeeAuthenticator } from "./ITeeAuthenticator";
