/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface INitroProverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "verifyAttestation"
      | "verifyAttestationStep1"
      | "verifyAttestationStep2"
      | "verifyAttestationStep3"
      | "verifyAttestationStep4"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verifyAttestation",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttestationStep1",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttestationStep2",
    values: [BytesLike[], BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttestationStep3",
    values: [BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAttestationStep4",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttestationStep1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttestationStep2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttestationStep3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAttestationStep4",
    data: BytesLike
  ): Result;
}

export interface INitroProver extends BaseContract {
  connect(runner?: ContractRunner | null): INitroProver;
  waitForDeployment(): Promise<this>;

  interface: INitroProverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifyAttestation: TypedContractMethod<
    [attestation: BytesLike, maxAge: BigNumberish],
    [[string, string, string]],
    "view"
  >;

  verifyAttestationStep1: TypedContractMethod<
    [attestation: BytesLike, max_age: BigNumberish],
    [
      [string[], string, string[], string, string, string] & {
        attestation_decoded: string[];
        certificate: string;
        cabundle: string[];
        enclaveKey: string;
        userData: string;
        rawPcrs: string;
      }
    ],
    "view"
  >;

  verifyAttestationStep2: TypedContractMethod<
    [cabundle: BytesLike[], index: BigNumberish, parentPubKey: BytesLike],
    [string],
    "view"
  >;

  verifyAttestationStep3: TypedContractMethod<
    [
      attestation_decoded: BytesLike[],
      certificate: BytesLike,
      parentPubKey: BytesLike
    ],
    [
      [string, string, string] & {
        attestationSig: string;
        pubKey: string;
        bufBufBuf: string;
      }
    ],
    "view"
  >;

  verifyAttestationStep4: TypedContractMethod<
    [attestationSig: BytesLike, pubKey: BytesLike, buf: BytesLike],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifyAttestation"
  ): TypedContractMethod<
    [attestation: BytesLike, maxAge: BigNumberish],
    [[string, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyAttestationStep1"
  ): TypedContractMethod<
    [attestation: BytesLike, max_age: BigNumberish],
    [
      [string[], string, string[], string, string, string] & {
        attestation_decoded: string[];
        certificate: string;
        cabundle: string[];
        enclaveKey: string;
        userData: string;
        rawPcrs: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyAttestationStep2"
  ): TypedContractMethod<
    [cabundle: BytesLike[], index: BigNumberish, parentPubKey: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyAttestationStep3"
  ): TypedContractMethod<
    [
      attestation_decoded: BytesLike[],
      certificate: BytesLike,
      parentPubKey: BytesLike
    ],
    [
      [string, string, string] & {
        attestationSig: string;
        pubKey: string;
        bufBufBuf: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyAttestationStep4"
  ): TypedContractMethod<
    [attestationSig: BytesLike, pubKey: BytesLike, buf: BytesLike],
    [void],
    "view"
  >;

  filters: {};
}
