/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Structs {
  export type PendingRequestStruct = {
    timestamp: BigNumberish;
    depositAmount: BigNumberish;
    maxFeeValue: BigNumberish;
    requestId: BytesLike;
    payload: BytesLike;
    sender: AddressLike;
    applicationId: BigNumberish;
    protocolVersion: BigNumberish;
    requestType: BigNumberish;
  };

  export type PendingRequestStructOutput = [
    timestamp: bigint,
    depositAmount: bigint,
    maxFeeValue: bigint,
    requestId: string,
    payload: string,
    sender: string,
    applicationId: bigint,
    protocolVersion: bigint,
    requestType: bigint
  ] & {
    timestamp: bigint;
    depositAmount: bigint;
    maxFeeValue: bigint;
    requestId: string;
    payload: string;
    sender: string;
    applicationId: bigint;
    protocolVersion: bigint;
    requestType: bigint;
  };

  export type WithdrawalRequestStruct = {
    receiver: AddressLike;
    amount: BigNumberish;
  };

  export type WithdrawalRequestStructOutput = [
    receiver: string,
    amount: bigint
  ] & { receiver: string; amount: bigint };
}

export interface IProcessorEndpointInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "generateRequestId"
      | "getNextPendingRequest"
      | "getPendingRequests"
      | "getPendingRequestsPage"
      | "getPendingRequestsSize"
      | "isCurrentPendingRequest"
      | "markRequestFailed"
      | "stateUpdate"
      | "submitRequest"
      | "updateFeeCollector"
      | "updateQueueThreshold"
      | "withdrawPayments"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeCollectorUpdated"
      | "PaymentWithdrawn"
      | "QueueThresholdUpdated"
      | "Refund"
      | "ReportGenerated"
      | "RequestCompleted"
      | "RequestSubmitted"
      | "StateRootUpdate"
      | "UserEvent"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "generateRequestId",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextPendingRequest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequestsPage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequestsSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isCurrentPendingRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markRequestFailed",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "stateUpdate",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike[],
      string[],
      Structs.WithdrawalRequestStruct[],
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRequest",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateQueueThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPayments",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "generateRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextPendingRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequestsPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequestsSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCurrentPendingRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markRequestFailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateQueueThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPayments",
    data: BytesLike
  ): Result;
}

export namespace FeeCollectorUpdatedEvent {
  export type InputTuple = [newFeeCollector: AddressLike];
  export type OutputTuple = [newFeeCollector: string];
  export interface OutputObject {
    newFeeCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentWithdrawnEvent {
  export type InputTuple = [payee: AddressLike, amount: BigNumberish];
  export type OutputTuple = [payee: string, amount: bigint];
  export interface OutputObject {
    payee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QueueThresholdUpdatedEvent {
  export type InputTuple = [newThreshold: BigNumberish];
  export type OutputTuple = [newThreshold: bigint];
  export interface OutputObject {
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportGeneratedEvent {
  export type InputTuple = [applicationId: BigNumberish, requestId: BytesLike];
  export type OutputTuple = [applicationId: bigint, requestId: string];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCompletedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    applicationFees: BigNumberish,
    status: BigNumberish,
    errorCode: BigNumberish,
    errorMessage: string
  ];
  export type OutputTuple = [
    requestId: string,
    applicationFees: bigint,
    status: bigint,
    errorCode: bigint,
    errorMessage: string
  ];
  export interface OutputObject {
    requestId: string;
    applicationFees: bigint;
    status: bigint;
    errorCode: bigint;
    errorMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestSubmittedEvent {
  export type InputTuple = [requestId: BytesLike, sender: AddressLike];
  export type OutputTuple = [requestId: string, sender: string];
  export interface OutputObject {
    requestId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StateRootUpdateEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    oldStateRoot: BytesLike,
    newStateRoot: BytesLike
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    oldStateRoot: string,
    newStateRoot: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    oldStateRoot: string;
    newStateRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserEventEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    eventSubType: string,
    encryptedData: BytesLike
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    eventSubType: string,
    encryptedData: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    eventSubType: string;
    encryptedData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IProcessorEndpoint extends BaseContract {
  connect(runner?: ContractRunner | null): IProcessorEndpoint;
  waitForDeployment(): Promise<this>;

  interface: IProcessorEndpointInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  generateRequestId: TypedContractMethod<
    [
      sender: AddressLike,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      depositAmount: BigNumberish,
      idx: BigNumberish
    ],
    [string],
    "view"
  >;

  getNextPendingRequest: TypedContractMethod<
    [],
    [[Structs.PendingRequestStructOutput, string, boolean]],
    "view"
  >;

  getPendingRequests: TypedContractMethod<
    [],
    [Structs.PendingRequestStructOutput[]],
    "view"
  >;

  getPendingRequestsPage: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [Structs.PendingRequestStructOutput[]],
    "view"
  >;

  getPendingRequestsSize: TypedContractMethod<[], [bigint], "view">;

  isCurrentPendingRequest: TypedContractMethod<
    [requestId: BytesLike],
    [boolean],
    "view"
  >;

  markRequestFailed: TypedContractMethod<
    [requestId: BytesLike, errorCode: BigNumberish, errorMessage: string],
    [void],
    "nonpayable"
  >;

  stateUpdate: TypedContractMethod<
    [
      applicationId: BigNumberish,
      prevStateRoot: BytesLike,
      newStateRoot: BytesLike,
      processedRequestId: BytesLike,
      events: BytesLike[],
      eventSubTypes: string[],
      withdrawalRequests: Structs.WithdrawalRequestStruct[],
      refund: BigNumberish,
      applicationFees: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitRequest: TypedContractMethod<
    [
      protocolVersion: BigNumberish,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      depositAmount: BigNumberish,
      maxFeeValue: BigNumberish
    ],
    [string],
    "payable"
  >;

  updateFeeCollector: TypedContractMethod<
    [newFeeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  updateQueueThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawPayments: TypedContractMethod<
    [payee: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "generateRequestId"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      depositAmount: BigNumberish,
      idx: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNextPendingRequest"
  ): TypedContractMethod<
    [],
    [[Structs.PendingRequestStructOutput, string, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingRequests"
  ): TypedContractMethod<[], [Structs.PendingRequestStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getPendingRequestsPage"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [Structs.PendingRequestStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingRequestsSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isCurrentPendingRequest"
  ): TypedContractMethod<[requestId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markRequestFailed"
  ): TypedContractMethod<
    [requestId: BytesLike, errorCode: BigNumberish, errorMessage: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stateUpdate"
  ): TypedContractMethod<
    [
      applicationId: BigNumberish,
      prevStateRoot: BytesLike,
      newStateRoot: BytesLike,
      processedRequestId: BytesLike,
      events: BytesLike[],
      eventSubTypes: string[],
      withdrawalRequests: Structs.WithdrawalRequestStruct[],
      refund: BigNumberish,
      applicationFees: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitRequest"
  ): TypedContractMethod<
    [
      protocolVersion: BigNumberish,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      depositAmount: BigNumberish,
      maxFeeValue: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "updateFeeCollector"
  ): TypedContractMethod<[newFeeCollector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateQueueThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPayments"
  ): TypedContractMethod<[payee: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeeCollectorUpdated"
  ): TypedContractEvent<
    FeeCollectorUpdatedEvent.InputTuple,
    FeeCollectorUpdatedEvent.OutputTuple,
    FeeCollectorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentWithdrawn"
  ): TypedContractEvent<
    PaymentWithdrawnEvent.InputTuple,
    PaymentWithdrawnEvent.OutputTuple,
    PaymentWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "QueueThresholdUpdated"
  ): TypedContractEvent<
    QueueThresholdUpdatedEvent.InputTuple,
    QueueThresholdUpdatedEvent.OutputTuple,
    QueueThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Refund"
  ): TypedContractEvent<
    RefundEvent.InputTuple,
    RefundEvent.OutputTuple,
    RefundEvent.OutputObject
  >;
  getEvent(
    key: "ReportGenerated"
  ): TypedContractEvent<
    ReportGeneratedEvent.InputTuple,
    ReportGeneratedEvent.OutputTuple,
    ReportGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "RequestCompleted"
  ): TypedContractEvent<
    RequestCompletedEvent.InputTuple,
    RequestCompletedEvent.OutputTuple,
    RequestCompletedEvent.OutputObject
  >;
  getEvent(
    key: "RequestSubmitted"
  ): TypedContractEvent<
    RequestSubmittedEvent.InputTuple,
    RequestSubmittedEvent.OutputTuple,
    RequestSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "StateRootUpdate"
  ): TypedContractEvent<
    StateRootUpdateEvent.InputTuple,
    StateRootUpdateEvent.OutputTuple,
    StateRootUpdateEvent.OutputObject
  >;
  getEvent(
    key: "UserEvent"
  ): TypedContractEvent<
    UserEventEvent.InputTuple,
    UserEventEvent.OutputTuple,
    UserEventEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "FeeCollectorUpdated(address)": TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;
    FeeCollectorUpdated: TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;

    "PaymentWithdrawn(address,uint256)": TypedContractEvent<
      PaymentWithdrawnEvent.InputTuple,
      PaymentWithdrawnEvent.OutputTuple,
      PaymentWithdrawnEvent.OutputObject
    >;
    PaymentWithdrawn: TypedContractEvent<
      PaymentWithdrawnEvent.InputTuple,
      PaymentWithdrawnEvent.OutputTuple,
      PaymentWithdrawnEvent.OutputObject
    >;

    "QueueThresholdUpdated(uint256)": TypedContractEvent<
      QueueThresholdUpdatedEvent.InputTuple,
      QueueThresholdUpdatedEvent.OutputTuple,
      QueueThresholdUpdatedEvent.OutputObject
    >;
    QueueThresholdUpdated: TypedContractEvent<
      QueueThresholdUpdatedEvent.InputTuple,
      QueueThresholdUpdatedEvent.OutputTuple,
      QueueThresholdUpdatedEvent.OutputObject
    >;

    "Refund(uint64,bytes32,address,uint256)": TypedContractEvent<
      RefundEvent.InputTuple,
      RefundEvent.OutputTuple,
      RefundEvent.OutputObject
    >;
    Refund: TypedContractEvent<
      RefundEvent.InputTuple,
      RefundEvent.OutputTuple,
      RefundEvent.OutputObject
    >;

    "ReportGenerated(uint64,bytes32)": TypedContractEvent<
      ReportGeneratedEvent.InputTuple,
      ReportGeneratedEvent.OutputTuple,
      ReportGeneratedEvent.OutputObject
    >;
    ReportGenerated: TypedContractEvent<
      ReportGeneratedEvent.InputTuple,
      ReportGeneratedEvent.OutputTuple,
      ReportGeneratedEvent.OutputObject
    >;

    "RequestCompleted(bytes32,uint256,uint8,uint8,string)": TypedContractEvent<
      RequestCompletedEvent.InputTuple,
      RequestCompletedEvent.OutputTuple,
      RequestCompletedEvent.OutputObject
    >;
    RequestCompleted: TypedContractEvent<
      RequestCompletedEvent.InputTuple,
      RequestCompletedEvent.OutputTuple,
      RequestCompletedEvent.OutputObject
    >;

    "RequestSubmitted(bytes32,address)": TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;
    RequestSubmitted: TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;

    "StateRootUpdate(uint64,bytes32,bytes32,bytes32)": TypedContractEvent<
      StateRootUpdateEvent.InputTuple,
      StateRootUpdateEvent.OutputTuple,
      StateRootUpdateEvent.OutputObject
    >;
    StateRootUpdate: TypedContractEvent<
      StateRootUpdateEvent.InputTuple,
      StateRootUpdateEvent.OutputTuple,
      StateRootUpdateEvent.OutputObject
    >;

    "UserEvent(uint64,bytes32,string,bytes)": TypedContractEvent<
      UserEventEvent.InputTuple,
      UserEventEvent.OutputTuple,
      UserEventEvent.OutputObject
    >;
    UserEvent: TypedContractEvent<
      UserEventEvent.InputTuple,
      UserEventEvent.OutputTuple,
      UserEventEvent.OutputObject
    >;

    "Withdrawal(uint64,bytes32,address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
