/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Structs {
  export type PendingRequestStruct = {
    timestamp: BigNumberish;
    tokenAddress: AddressLike;
    assetAmount: BigNumberish;
    maxFeeValue: BigNumberish;
    requestId: BytesLike;
    payload: BytesLike;
    sender: AddressLike;
    facilitator: AddressLike;
    applicationId: BigNumberish;
    protocolVersion: BigNumberish;
    requestType: BigNumberish;
  };

  export type PendingRequestStructOutput = [
    timestamp: bigint,
    tokenAddress: string,
    assetAmount: bigint,
    maxFeeValue: bigint,
    requestId: string,
    payload: string,
    sender: string,
    facilitator: string,
    applicationId: bigint,
    protocolVersion: bigint,
    requestType: bigint
  ] & {
    timestamp: bigint;
    tokenAddress: string;
    assetAmount: bigint;
    maxFeeValue: bigint;
    requestId: string;
    payload: string;
    sender: string;
    facilitator: string;
    applicationId: bigint;
    protocolVersion: bigint;
    requestType: bigint;
  };

  export type EventDataStruct = { events: BytesLike[]; subTypes: BytesLike[] };

  export type EventDataStructOutput = [events: string[], subTypes: string[]] & {
    events: string[];
    subTypes: string[];
  };

  export type WithdrawalRequestStruct = {
    tokenAddress: AddressLike;
    receiver: AddressLike;
    amount: BigNumberish;
  };

  export type WithdrawalRequestStructOutput = [
    tokenAddress: string,
    receiver: string,
    amount: bigint
  ] & { tokenAddress: string; receiver: string; amount: bigint };
}

export interface IProcessorEndpointInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAllowedDeployer"
      | "appCustody"
      | "claim"
      | "generateRequestId"
      | "getFacilitatorNonce"
      | "getNextPendingRequest"
      | "getPendingRequests"
      | "getPendingRequestsPage"
      | "getPendingRequestsSize"
      | "isAllowedDeployer"
      | "isCurrentPendingRequest"
      | "pendingClaims"
      | "removeAllowedDeployer"
      | "stateUpdate"
      | "submitDeployRequest"
      | "submitRequest"
      | "submitRequestFor"
      | "totalAppCustody"
      | "totalPendingClaims"
      | "updateFeeCollector"
      | "updateMaxNumOfApplications"
      | "updateQueueThreshold"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AppEvent"
      | "DeployRequestCompleted"
      | "DeployRequestSubmitted"
      | "FeeCollectorUpdated"
      | "MaxNumberOfAppUpdated"
      | "PaymentWithdrawn"
      | "QueueThresholdUpdated"
      | "Refund"
      | "ReportGenerated"
      | "RequestCompleted"
      | "RequestSubmitted"
      | "StateRootUpdate"
      | "UserEvent"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAllowedDeployer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "appCustody",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "generateRequestId",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getFacilitatorNonce",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextPendingRequest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequestsPage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRequestsSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowedDeployer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCurrentPendingRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingClaims",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAllowedDeployer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stateUpdate",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      Structs.EventDataStruct,
      Structs.EventDataStruct,
      Structs.WithdrawalRequestStruct[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDeployRequest",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRequest",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRequestFor",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAppCustody",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPendingClaims",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaxNumOfApplications",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateQueueThreshold",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAllowedDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "appCustody", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "generateRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFacilitatorNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextPendingRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequestsPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRequestsSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAllowedDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCurrentPendingRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAllowedDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDeployRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRequestFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAppCustody",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPendingClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaxNumOfApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateQueueThreshold",
    data: BytesLike
  ): Result;
}

export namespace AppEventEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    eventSubType: BytesLike,
    data: BytesLike
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    eventSubType: string,
    data: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    eventSubType: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeployRequestCompletedEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    applicationFees: BigNumberish,
    status: BigNumberish,
    errorCode: BigNumberish,
    errorMessage: string
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    applicationFees: bigint,
    status: bigint,
    errorCode: bigint,
    errorMessage: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    applicationFees: bigint;
    status: bigint;
    errorCode: bigint;
    errorMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeployRequestSubmittedEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    sender: AddressLike
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    sender: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectorUpdatedEvent {
  export type InputTuple = [newFeeCollector: AddressLike];
  export type OutputTuple = [newFeeCollector: string];
  export interface OutputObject {
    newFeeCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxNumberOfAppUpdatedEvent {
  export type InputTuple = [oldMax: BigNumberish, newMax: BigNumberish];
  export type OutputTuple = [oldMax: bigint, newMax: bigint];
  export interface OutputObject {
    oldMax: bigint;
    newMax: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentWithdrawnEvent {
  export type InputTuple = [
    tokenAddress: AddressLike,
    payee: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    tokenAddress: string,
    payee: string,
    amount: bigint
  ];
  export interface OutputObject {
    tokenAddress: string;
    payee: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QueueThresholdUpdatedEvent {
  export type InputTuple = [newThreshold: BigNumberish];
  export type OutputTuple = [newThreshold: bigint];
  export interface OutputObject {
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    to: AddressLike,
    tokenAddress: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    to: string,
    tokenAddress: string,
    amount: bigint
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    to: string;
    tokenAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportGeneratedEvent {
  export type InputTuple = [applicationId: BigNumberish, requestId: BytesLike];
  export type OutputTuple = [applicationId: bigint, requestId: string];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCompletedEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    applicationFees: BigNumberish,
    status: BigNumberish,
    errorCode: BigNumberish,
    errorMessage: string
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    applicationFees: bigint,
    status: bigint,
    errorCode: bigint,
    errorMessage: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    applicationFees: bigint;
    status: bigint;
    errorCode: bigint;
    errorMessage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestSubmittedEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    sender: AddressLike,
    facilitator: AddressLike
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    sender: string,
    facilitator: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    sender: string;
    facilitator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StateRootUpdateEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    oldStateRoot: BytesLike,
    newStateRoot: BytesLike
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    oldStateRoot: string,
    newStateRoot: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    oldStateRoot: string;
    newStateRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserEventEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    eventSubType: BytesLike,
    encryptedData: BytesLike
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    eventSubType: string,
    encryptedData: string
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    eventSubType: string;
    encryptedData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    requestId: BytesLike,
    to: AddressLike,
    tokenAddress: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    applicationId: bigint,
    requestId: string,
    to: string,
    tokenAddress: string,
    amount: bigint
  ];
  export interface OutputObject {
    applicationId: bigint;
    requestId: string;
    to: string;
    tokenAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IProcessorEndpoint extends BaseContract {
  connect(runner?: ContractRunner | null): IProcessorEndpoint;
  waitForDeployment(): Promise<this>;

  interface: IProcessorEndpointInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAllowedDeployer: TypedContractMethod<
    [deployer: AddressLike],
    [void],
    "nonpayable"
  >;

  appCustody: TypedContractMethod<
    [applicationId: BigNumberish, tokenAddress: AddressLike],
    [bigint],
    "view"
  >;

  claim: TypedContractMethod<
    [tokenAddress: AddressLike, payee: AddressLike],
    [void],
    "nonpayable"
  >;

  generateRequestId: TypedContractMethod<
    [
      sender: AddressLike,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      tokenAddress: AddressLike,
      assetAmount: BigNumberish,
      idx: BigNumberish
    ],
    [string],
    "view"
  >;

  getFacilitatorNonce: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getNextPendingRequest: TypedContractMethod<
    [],
    [[Structs.PendingRequestStructOutput, string, boolean]],
    "view"
  >;

  getPendingRequests: TypedContractMethod<
    [],
    [Structs.PendingRequestStructOutput[]],
    "view"
  >;

  getPendingRequestsPage: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [Structs.PendingRequestStructOutput[]],
    "view"
  >;

  getPendingRequestsSize: TypedContractMethod<[], [bigint], "view">;

  isAllowedDeployer: TypedContractMethod<
    [deployer: AddressLike],
    [boolean],
    "view"
  >;

  isCurrentPendingRequest: TypedContractMethod<
    [requestId: BytesLike],
    [boolean],
    "view"
  >;

  pendingClaims: TypedContractMethod<
    [tokenAddress: AddressLike, payee: AddressLike],
    [bigint],
    "view"
  >;

  removeAllowedDeployer: TypedContractMethod<
    [deployer: AddressLike],
    [void],
    "nonpayable"
  >;

  stateUpdate: TypedContractMethod<
    [
      applicationId: BigNumberish,
      prevStateRoot: BytesLike,
      newStateRoot: BytesLike,
      processedRequestId: BytesLike,
      userEventData: Structs.EventDataStruct,
      appEventData: Structs.EventDataStruct,
      withdrawalRequests: Structs.WithdrawalRequestStruct[],
      refund: BigNumberish,
      applicationFees: BigNumberish,
      errorCode: BigNumberish,
      errorMsg: string,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitDeployRequest: TypedContractMethod<
    [protocolVersion: BigNumberish, payload: BytesLike],
    [string],
    "payable"
  >;

  submitRequest: TypedContractMethod<
    [
      protocolVersion: BigNumberish,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      tokenAddress: AddressLike,
      assetAmount: BigNumberish,
      maxFeeValue: BigNumberish
    ],
    [string],
    "payable"
  >;

  submitRequestFor: TypedContractMethod<
    [
      sender: AddressLike,
      protocolVersion: BigNumberish,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      tokenAddress: AddressLike,
      assetAmount: BigNumberish,
      deadline: BigNumberish,
      requestSignature: BytesLike,
      depositPermit: BytesLike
    ],
    [string],
    "payable"
  >;

  totalAppCustody: TypedContractMethod<
    [tokenAddress: AddressLike],
    [bigint],
    "view"
  >;

  totalPendingClaims: TypedContractMethod<
    [tokenAddress: AddressLike],
    [bigint],
    "view"
  >;

  updateFeeCollector: TypedContractMethod<
    [newFeeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  updateMaxNumOfApplications: TypedContractMethod<
    [newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateQueueThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAllowedDeployer"
  ): TypedContractMethod<[deployer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "appCustody"
  ): TypedContractMethod<
    [applicationId: BigNumberish, tokenAddress: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, payee: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "generateRequestId"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      tokenAddress: AddressLike,
      assetAmount: BigNumberish,
      idx: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFacilitatorNonce"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNextPendingRequest"
  ): TypedContractMethod<
    [],
    [[Structs.PendingRequestStructOutput, string, boolean]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingRequests"
  ): TypedContractMethod<[], [Structs.PendingRequestStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getPendingRequestsPage"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [Structs.PendingRequestStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingRequestsSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAllowedDeployer"
  ): TypedContractMethod<[deployer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCurrentPendingRequest"
  ): TypedContractMethod<[requestId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingClaims"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, payee: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeAllowedDeployer"
  ): TypedContractMethod<[deployer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stateUpdate"
  ): TypedContractMethod<
    [
      applicationId: BigNumberish,
      prevStateRoot: BytesLike,
      newStateRoot: BytesLike,
      processedRequestId: BytesLike,
      userEventData: Structs.EventDataStruct,
      appEventData: Structs.EventDataStruct,
      withdrawalRequests: Structs.WithdrawalRequestStruct[],
      refund: BigNumberish,
      applicationFees: BigNumberish,
      errorCode: BigNumberish,
      errorMsg: string,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDeployRequest"
  ): TypedContractMethod<
    [protocolVersion: BigNumberish, payload: BytesLike],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "submitRequest"
  ): TypedContractMethod<
    [
      protocolVersion: BigNumberish,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      tokenAddress: AddressLike,
      assetAmount: BigNumberish,
      maxFeeValue: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "submitRequestFor"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      protocolVersion: BigNumberish,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      tokenAddress: AddressLike,
      assetAmount: BigNumberish,
      deadline: BigNumberish,
      requestSignature: BytesLike,
      depositPermit: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "totalAppCustody"
  ): TypedContractMethod<[tokenAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPendingClaims"
  ): TypedContractMethod<[tokenAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateFeeCollector"
  ): TypedContractMethod<[newFeeCollector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMaxNumOfApplications"
  ): TypedContractMethod<[newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateQueueThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AppEvent"
  ): TypedContractEvent<
    AppEventEvent.InputTuple,
    AppEventEvent.OutputTuple,
    AppEventEvent.OutputObject
  >;
  getEvent(
    key: "DeployRequestCompleted"
  ): TypedContractEvent<
    DeployRequestCompletedEvent.InputTuple,
    DeployRequestCompletedEvent.OutputTuple,
    DeployRequestCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DeployRequestSubmitted"
  ): TypedContractEvent<
    DeployRequestSubmittedEvent.InputTuple,
    DeployRequestSubmittedEvent.OutputTuple,
    DeployRequestSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollectorUpdated"
  ): TypedContractEvent<
    FeeCollectorUpdatedEvent.InputTuple,
    FeeCollectorUpdatedEvent.OutputTuple,
    FeeCollectorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxNumberOfAppUpdated"
  ): TypedContractEvent<
    MaxNumberOfAppUpdatedEvent.InputTuple,
    MaxNumberOfAppUpdatedEvent.OutputTuple,
    MaxNumberOfAppUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentWithdrawn"
  ): TypedContractEvent<
    PaymentWithdrawnEvent.InputTuple,
    PaymentWithdrawnEvent.OutputTuple,
    PaymentWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "QueueThresholdUpdated"
  ): TypedContractEvent<
    QueueThresholdUpdatedEvent.InputTuple,
    QueueThresholdUpdatedEvent.OutputTuple,
    QueueThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Refund"
  ): TypedContractEvent<
    RefundEvent.InputTuple,
    RefundEvent.OutputTuple,
    RefundEvent.OutputObject
  >;
  getEvent(
    key: "ReportGenerated"
  ): TypedContractEvent<
    ReportGeneratedEvent.InputTuple,
    ReportGeneratedEvent.OutputTuple,
    ReportGeneratedEvent.OutputObject
  >;
  getEvent(
    key: "RequestCompleted"
  ): TypedContractEvent<
    RequestCompletedEvent.InputTuple,
    RequestCompletedEvent.OutputTuple,
    RequestCompletedEvent.OutputObject
  >;
  getEvent(
    key: "RequestSubmitted"
  ): TypedContractEvent<
    RequestSubmittedEvent.InputTuple,
    RequestSubmittedEvent.OutputTuple,
    RequestSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "StateRootUpdate"
  ): TypedContractEvent<
    StateRootUpdateEvent.InputTuple,
    StateRootUpdateEvent.OutputTuple,
    StateRootUpdateEvent.OutputObject
  >;
  getEvent(
    key: "UserEvent"
  ): TypedContractEvent<
    UserEventEvent.InputTuple,
    UserEventEvent.OutputTuple,
    UserEventEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "AppEvent(uint64,bytes32,bytes32,bytes)": TypedContractEvent<
      AppEventEvent.InputTuple,
      AppEventEvent.OutputTuple,
      AppEventEvent.OutputObject
    >;
    AppEvent: TypedContractEvent<
      AppEventEvent.InputTuple,
      AppEventEvent.OutputTuple,
      AppEventEvent.OutputObject
    >;

    "DeployRequestCompleted(uint64,bytes32,uint256,uint8,uint8,string)": TypedContractEvent<
      DeployRequestCompletedEvent.InputTuple,
      DeployRequestCompletedEvent.OutputTuple,
      DeployRequestCompletedEvent.OutputObject
    >;
    DeployRequestCompleted: TypedContractEvent<
      DeployRequestCompletedEvent.InputTuple,
      DeployRequestCompletedEvent.OutputTuple,
      DeployRequestCompletedEvent.OutputObject
    >;

    "DeployRequestSubmitted(uint64,bytes32,address)": TypedContractEvent<
      DeployRequestSubmittedEvent.InputTuple,
      DeployRequestSubmittedEvent.OutputTuple,
      DeployRequestSubmittedEvent.OutputObject
    >;
    DeployRequestSubmitted: TypedContractEvent<
      DeployRequestSubmittedEvent.InputTuple,
      DeployRequestSubmittedEvent.OutputTuple,
      DeployRequestSubmittedEvent.OutputObject
    >;

    "FeeCollectorUpdated(address)": TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;
    FeeCollectorUpdated: TypedContractEvent<
      FeeCollectorUpdatedEvent.InputTuple,
      FeeCollectorUpdatedEvent.OutputTuple,
      FeeCollectorUpdatedEvent.OutputObject
    >;

    "MaxNumberOfAppUpdated(uint256,uint256)": TypedContractEvent<
      MaxNumberOfAppUpdatedEvent.InputTuple,
      MaxNumberOfAppUpdatedEvent.OutputTuple,
      MaxNumberOfAppUpdatedEvent.OutputObject
    >;
    MaxNumberOfAppUpdated: TypedContractEvent<
      MaxNumberOfAppUpdatedEvent.InputTuple,
      MaxNumberOfAppUpdatedEvent.OutputTuple,
      MaxNumberOfAppUpdatedEvent.OutputObject
    >;

    "PaymentWithdrawn(address,address,uint256)": TypedContractEvent<
      PaymentWithdrawnEvent.InputTuple,
      PaymentWithdrawnEvent.OutputTuple,
      PaymentWithdrawnEvent.OutputObject
    >;
    PaymentWithdrawn: TypedContractEvent<
      PaymentWithdrawnEvent.InputTuple,
      PaymentWithdrawnEvent.OutputTuple,
      PaymentWithdrawnEvent.OutputObject
    >;

    "QueueThresholdUpdated(uint256)": TypedContractEvent<
      QueueThresholdUpdatedEvent.InputTuple,
      QueueThresholdUpdatedEvent.OutputTuple,
      QueueThresholdUpdatedEvent.OutputObject
    >;
    QueueThresholdUpdated: TypedContractEvent<
      QueueThresholdUpdatedEvent.InputTuple,
      QueueThresholdUpdatedEvent.OutputTuple,
      QueueThresholdUpdatedEvent.OutputObject
    >;

    "Refund(uint64,bytes32,address,address,uint256)": TypedContractEvent<
      RefundEvent.InputTuple,
      RefundEvent.OutputTuple,
      RefundEvent.OutputObject
    >;
    Refund: TypedContractEvent<
      RefundEvent.InputTuple,
      RefundEvent.OutputTuple,
      RefundEvent.OutputObject
    >;

    "ReportGenerated(uint64,bytes32)": TypedContractEvent<
      ReportGeneratedEvent.InputTuple,
      ReportGeneratedEvent.OutputTuple,
      ReportGeneratedEvent.OutputObject
    >;
    ReportGenerated: TypedContractEvent<
      ReportGeneratedEvent.InputTuple,
      ReportGeneratedEvent.OutputTuple,
      ReportGeneratedEvent.OutputObject
    >;

    "RequestCompleted(uint64,bytes32,uint256,uint8,uint8,string)": TypedContractEvent<
      RequestCompletedEvent.InputTuple,
      RequestCompletedEvent.OutputTuple,
      RequestCompletedEvent.OutputObject
    >;
    RequestCompleted: TypedContractEvent<
      RequestCompletedEvent.InputTuple,
      RequestCompletedEvent.OutputTuple,
      RequestCompletedEvent.OutputObject
    >;

    "RequestSubmitted(uint64,bytes32,address,address)": TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;
    RequestSubmitted: TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;

    "StateRootUpdate(uint64,bytes32,bytes32,bytes32)": TypedContractEvent<
      StateRootUpdateEvent.InputTuple,
      StateRootUpdateEvent.OutputTuple,
      StateRootUpdateEvent.OutputObject
    >;
    StateRootUpdate: TypedContractEvent<
      StateRootUpdateEvent.InputTuple,
      StateRootUpdateEvent.OutputTuple,
      StateRootUpdateEvent.OutputObject
    >;

    "UserEvent(uint64,bytes32,bytes32,bytes)": TypedContractEvent<
      UserEventEvent.InputTuple,
      UserEventEvent.OutputTuple,
      UserEventEvent.OutputObject
    >;
    UserEvent: TypedContractEvent<
      UserEventEvent.InputTuple,
      UserEventEvent.OutputTuple,
      UserEventEvent.OutputObject
    >;

    "Withdrawal(uint64,bytes32,address,address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
