/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Structs {
  export type EventDataStruct = { events: BytesLike[]; subTypes: string[] };

  export type EventDataStructOutput = [events: string[], subTypes: string[]] & {
    events: string[];
    subTypes: string[];
  };

  export type WithdrawalRequestStruct = {
    tokenAddress: AddressLike;
    receiver: AddressLike;
    amount: BigNumberish;
  };

  export type WithdrawalRequestStructOutput = [
    tokenAddress: string,
    receiver: string,
    amount: bigint
  ] & { tokenAddress: string; receiver: string; amount: bigint };

  export type SignatureParamsStruct = {
    applicationId: BigNumberish;
    prevStateRoot: BytesLike;
    newStateRoot: BytesLike;
    processedRequestId: BytesLike;
    userEvents: Structs.EventDataStruct;
    appEvents: Structs.EventDataStruct;
    withdrawalRequests: Structs.WithdrawalRequestStruct[];
    refundAmount: BigNumberish;
    applicationFee: BigNumberish;
    errorCode: BigNumberish;
    errorMsg: string;
  };

  export type SignatureParamsStructOutput = [
    applicationId: bigint,
    prevStateRoot: string,
    newStateRoot: string,
    processedRequestId: string,
    userEvents: Structs.EventDataStructOutput,
    appEvents: Structs.EventDataStructOutput,
    withdrawalRequests: Structs.WithdrawalRequestStructOutput[],
    refundAmount: bigint,
    applicationFee: bigint,
    errorCode: bigint,
    errorMsg: string
  ] & {
    applicationId: bigint;
    prevStateRoot: string;
    newStateRoot: string;
    processedRequestId: string;
    userEvents: Structs.EventDataStructOutput;
    appEvents: Structs.EventDataStructOutput;
    withdrawalRequests: Structs.WithdrawalRequestStructOutput[];
    refundAmount: bigint;
    applicationFee: bigint;
    errorCode: bigint;
    errorMsg: string;
  };
}

export interface AbstractTeeAuthenticatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PK_LENGTH"
      | "checkSignature"
      | "getPubSecp521r1"
      | "getTeeSigner"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "PK_LENGTH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkSignature",
    values: [Structs.SignatureParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPubSecp521r1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTeeSigner",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "PK_LENGTH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPubSecp521r1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTeeSigner",
    data: BytesLike
  ): Result;
}

export interface AbstractTeeAuthenticator extends BaseContract {
  connect(runner?: ContractRunner | null): AbstractTeeAuthenticator;
  waitForDeployment(): Promise<this>;

  interface: AbstractTeeAuthenticatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PK_LENGTH: TypedContractMethod<[], [bigint], "view">;

  checkSignature: TypedContractMethod<
    [params: Structs.SignatureParamsStruct, signature: BytesLike],
    [boolean],
    "view"
  >;

  getPubSecp521r1: TypedContractMethod<[], [string], "view">;

  getTeeSigner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PK_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkSignature"
  ): TypedContractMethod<
    [params: Structs.SignatureParamsStruct, signature: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPubSecp521r1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTeeSigner"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
