/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DefaultAuthorityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAllowedAuthority"
      | "checkAuthorityIsAllowed"
      | "owner"
      | "removeAllowedAuthority"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddedAuthority"
      | "OwnershipTransferred"
      | "RemovedAuthority"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAllowedAuthority",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAuthorityIsAllowed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAllowedAuthority",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAllowedAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAuthorityIsAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAllowedAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AddedAuthorityEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    authority: AddressLike
  ];
  export type OutputTuple = [applicationId: bigint, authority: string];
  export interface OutputObject {
    applicationId: bigint;
    authority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemovedAuthorityEvent {
  export type InputTuple = [
    applicationId: BigNumberish,
    authority: AddressLike
  ];
  export type OutputTuple = [applicationId: bigint, authority: string];
  export interface OutputObject {
    applicationId: bigint;
    authority: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DefaultAuthority extends BaseContract {
  connect(runner?: ContractRunner | null): DefaultAuthority;
  waitForDeployment(): Promise<this>;

  interface: DefaultAuthorityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAllowedAuthority: TypedContractMethod<
    [applicationId: BigNumberish, authority: AddressLike],
    [void],
    "nonpayable"
  >;

  checkAuthorityIsAllowed: TypedContractMethod<
    [applicationId: BigNumberish, authority: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeAllowedAuthority: TypedContractMethod<
    [applicationId: BigNumberish, authority: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAllowedAuthority"
  ): TypedContractMethod<
    [applicationId: BigNumberish, authority: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkAuthorityIsAllowed"
  ): TypedContractMethod<
    [applicationId: BigNumberish, authority: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAllowedAuthority"
  ): TypedContractMethod<
    [applicationId: BigNumberish, authority: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AddedAuthority"
  ): TypedContractEvent<
    AddedAuthorityEvent.InputTuple,
    AddedAuthorityEvent.OutputTuple,
    AddedAuthorityEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RemovedAuthority"
  ): TypedContractEvent<
    RemovedAuthorityEvent.InputTuple,
    RemovedAuthorityEvent.OutputTuple,
    RemovedAuthorityEvent.OutputObject
  >;

  filters: {
    "AddedAuthority(uint256,address)": TypedContractEvent<
      AddedAuthorityEvent.InputTuple,
      AddedAuthorityEvent.OutputTuple,
      AddedAuthorityEvent.OutputObject
    >;
    AddedAuthority: TypedContractEvent<
      AddedAuthorityEvent.InputTuple,
      AddedAuthorityEvent.OutputTuple,
      AddedAuthorityEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RemovedAuthority(uint256,address)": TypedContractEvent<
      RemovedAuthorityEvent.InputTuple,
      RemovedAuthorityEvent.OutputTuple,
      RemovedAuthorityEvent.OutputObject
    >;
    RemovedAuthority: TypedContractEvent<
      RemovedAuthorityEvent.InputTuple,
      RemovedAuthorityEvent.OutputTuple,
      RemovedAuthorityEvent.OutputObject
    >;
  };
}
