/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Structs {
  export type EventDataStruct = { events: BytesLike[]; subTypes: string[] };

  export type EventDataStructOutput = [events: string[], subTypes: string[]] & {
    events: string[];
    subTypes: string[];
  };

  export type WithdrawalRequestStruct = {
    tokenAddress: AddressLike;
    receiver: AddressLike;
    amount: BigNumberish;
  };

  export type WithdrawalRequestStructOutput = [
    tokenAddress: string,
    receiver: string,
    amount: bigint
  ] & { tokenAddress: string; receiver: string; amount: bigint };

  export type SignatureParamsStruct = {
    applicationId: BigNumberish;
    prevStateRoot: BytesLike;
    newStateRoot: BytesLike;
    processedRequestId: BytesLike;
    userEvents: Structs.EventDataStruct;
    appEvents: Structs.EventDataStruct;
    withdrawalRequests: Structs.WithdrawalRequestStruct[];
    refundAmount: BigNumberish;
    applicationFee: BigNumberish;
    errorCode: BigNumberish;
    errorMsg: string;
  };

  export type SignatureParamsStructOutput = [
    applicationId: bigint,
    prevStateRoot: string,
    newStateRoot: string,
    processedRequestId: string,
    userEvents: Structs.EventDataStructOutput,
    appEvents: Structs.EventDataStructOutput,
    withdrawalRequests: Structs.WithdrawalRequestStructOutput[],
    refundAmount: bigint,
    applicationFee: bigint,
    errorCode: bigint,
    errorMsg: string
  ] & {
    applicationId: bigint;
    prevStateRoot: string;
    newStateRoot: string;
    processedRequestId: string;
    userEvents: Structs.EventDataStructOutput;
    appEvents: Structs.EventDataStructOutput;
    withdrawalRequests: Structs.WithdrawalRequestStructOutput[];
    refundAmount: bigint;
    applicationFee: bigint;
    errorCode: bigint;
    errorMsg: string;
  };
}

export interface TeeAuthenticatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PK_LENGTH"
      | "checkSignature"
      | "currentUpdateStep"
      | "getPubSecp521r1"
      | "getStep2TotalLength"
      | "getTeeSigner"
      | "maxVerificationAge"
      | "nitroProver"
      | "owner"
      | "pcr0"
      | "pubSecp521r1"
      | "renounceOwnership"
      | "step2CurrentIndex"
      | "teeSigner"
      | "transferOwnership"
      | "updatePcr0"
      | "updateTee"
      | "updateTeeStep1"
      | "updateTeeStep2"
      | "updateTeeStep3"
      | "updateTeeStep4"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PcrZeroUpdate"
      | "TeeUpdate"
  ): EventFragment;

  encodeFunctionData(functionFragment: "PK_LENGTH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkSignature",
    values: [Structs.SignatureParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentUpdateStep",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPubSecp521r1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStep2TotalLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTeeSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxVerificationAge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nitroProver",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pcr0", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pubSecp521r1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "step2CurrentIndex",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "teeSigner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePcr0",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTee",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTeeStep1",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTeeStep2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateTeeStep3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateTeeStep4",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "PK_LENGTH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentUpdateStep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPubSecp521r1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStep2TotalLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTeeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxVerificationAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nitroProver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pcr0", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pubSecp521r1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "step2CurrentIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teeSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updatePcr0", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateTee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTeeStep1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTeeStep2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTeeStep3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTeeStep4",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PcrZeroUpdateEvent {
  export type InputTuple = [oldPcr0: BytesLike, newPcr0: BytesLike];
  export type OutputTuple = [oldPcr0: string, newPcr0: string];
  export interface OutputObject {
    oldPcr0: string;
    newPcr0: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TeeUpdateEvent {
  export type InputTuple = [
    oldTee: AddressLike,
    newTee: AddressLike,
    oldPubSecp521r1: BytesLike,
    newPubSecp521r1: BytesLike
  ];
  export type OutputTuple = [
    oldTee: string,
    newTee: string,
    oldPubSecp521r1: string,
    newPubSecp521r1: string
  ];
  export interface OutputObject {
    oldTee: string;
    newTee: string;
    oldPubSecp521r1: string;
    newPubSecp521r1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TeeAuthenticator extends BaseContract {
  connect(runner?: ContractRunner | null): TeeAuthenticator;
  waitForDeployment(): Promise<this>;

  interface: TeeAuthenticatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PK_LENGTH: TypedContractMethod<[], [bigint], "view">;

  checkSignature: TypedContractMethod<
    [params: Structs.SignatureParamsStruct, signature: BytesLike],
    [boolean],
    "view"
  >;

  currentUpdateStep: TypedContractMethod<[], [bigint], "view">;

  getPubSecp521r1: TypedContractMethod<[], [string], "view">;

  getStep2TotalLength: TypedContractMethod<[], [bigint], "view">;

  getTeeSigner: TypedContractMethod<[], [string], "view">;

  maxVerificationAge: TypedContractMethod<[], [bigint], "view">;

  nitroProver: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pcr0: TypedContractMethod<[], [string], "view">;

  pubSecp521r1: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  step2CurrentIndex: TypedContractMethod<[], [bigint], "view">;

  teeSigner: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePcr0: TypedContractMethod<[newPcr0: BytesLike], [void], "nonpayable">;

  updateTee: TypedContractMethod<
    [attestation: BytesLike],
    [void],
    "nonpayable"
  >;

  updateTeeStep1: TypedContractMethod<
    [attestation: BytesLike],
    [void],
    "nonpayable"
  >;

  updateTeeStep2: TypedContractMethod<[], [void], "nonpayable">;

  updateTeeStep3: TypedContractMethod<[], [void], "nonpayable">;

  updateTeeStep4: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PK_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkSignature"
  ): TypedContractMethod<
    [params: Structs.SignatureParamsStruct, signature: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "currentUpdateStep"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPubSecp521r1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getStep2TotalLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTeeSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "maxVerificationAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nitroProver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pcr0"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pubSecp521r1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "step2CurrentIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "teeSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePcr0"
  ): TypedContractMethod<[newPcr0: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTee"
  ): TypedContractMethod<[attestation: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTeeStep1"
  ): TypedContractMethod<[attestation: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTeeStep2"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTeeStep3"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTeeStep4"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PcrZeroUpdate"
  ): TypedContractEvent<
    PcrZeroUpdateEvent.InputTuple,
    PcrZeroUpdateEvent.OutputTuple,
    PcrZeroUpdateEvent.OutputObject
  >;
  getEvent(
    key: "TeeUpdate"
  ): TypedContractEvent<
    TeeUpdateEvent.InputTuple,
    TeeUpdateEvent.OutputTuple,
    TeeUpdateEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PcrZeroUpdate(bytes,bytes)": TypedContractEvent<
      PcrZeroUpdateEvent.InputTuple,
      PcrZeroUpdateEvent.OutputTuple,
      PcrZeroUpdateEvent.OutputObject
    >;
    PcrZeroUpdate: TypedContractEvent<
      PcrZeroUpdateEvent.InputTuple,
      PcrZeroUpdateEvent.OutputTuple,
      PcrZeroUpdateEvent.OutputObject
    >;

    "TeeUpdate(address,address,bytes,bytes)": TypedContractEvent<
      TeeUpdateEvent.InputTuple,
      TeeUpdateEvent.OutputTuple,
      TeeUpdateEvent.OutputObject
    >;
    TeeUpdate: TypedContractEvent<
      TeeUpdateEvent.InputTuple,
      TeeUpdateEvent.OutputTuple,
      TeeUpdateEvent.OutputObject
    >;
  };
}
