/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  FallbackFailure,
  FallbackFailureInterface,
} from "../../../contracts/mocks/FallbackFailure";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "contract ProcessorEndpoint",
        name: "processorEndpoint",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "protocolVersion",
        type: "uint8",
      },
      {
        internalType: "uint64",
        name: "applicationId",
        type: "uint64",
      },
      {
        internalType: "enum Structs.RequestType",
        name: "requestType",
        type: "uint8",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "assetAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxFeeValue",
        type: "uint256",
      },
    ],
    name: "insertRequestOnProcessorEndpoint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080806040523460155761025f908161001b8239f35b600080fdfe608080604052600436101561008d575b5036156100525760405162461bcd60e51b815260206004820152601460248201527311985b1b189858dac81b9bdd08185b1b1bddd95960621b6044820152606490fd5b60405162461bcd60e51b8152602060048201526013602482015272149958d95a5d99481b9bdd08185b1b1bddd959606a1b6044820152606490fd5b60003560e01c638d1bad2a0361000f57610100366003190112610224576004356001600160a01b03811691908290036102245760243560ff81168091036102245760443567ffffffffffffffff811680910361022457606435936004851015610224576084359167ffffffffffffffff831161022457366023840112156102245782600401359367ffffffffffffffff85116102245736602486860101116102245760a4356001600160a01b0381169490859003610224578587956020976024889694879561010497632fbfa0d560e01b885260048801528287015260009c604487015260e060648701528260e4870152018585013789848385010152608483015260c43560a483015260e43560c4830152601f8019910116810103019134905af18015610219576101bd575080f35b906020913d602011610211575b601f8301601f191681019267ffffffffffffffff8411828510176101fd5760209293604052810103126101fa5780f35b80fd5b634e487b7160e01b83526041600452602483fd5b3d92506101ca565b6040513d84823e3d90fd5b600080fdfea2646970667358221220cf7f99b5285137fd9f912df087aee05bdac54344de8e92191c23cf8ac66a494064736f6c634300081c0033";

type FallbackFailureConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FallbackFailureConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FallbackFailure__factory extends ContractFactory {
  constructor(...args: FallbackFailureConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FallbackFailure & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): FallbackFailure__factory {
    return super.connect(runner) as FallbackFailure__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FallbackFailureInterface {
    return new Interface(_abi) as FallbackFailureInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FallbackFailure {
    return new Contract(address, _abi, runner) as unknown as FallbackFailure;
  }
}
