/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  FallbackFailure,
  FallbackFailureInterface,
} from "../../../contracts/mocks/FallbackFailure";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "contract ProcessorEndpoint",
        name: "processorEndpoint",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "protocolVersion",
        type: "uint8",
      },
      {
        internalType: "uint64",
        name: "applicationId",
        type: "uint64",
      },
      {
        internalType: "enum Structs.RequestType",
        name: "requestType",
        type: "uint8",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxFeeValue",
        type: "uint256",
      },
    ],
    name: "insertRequestOnProcessorEndpoint",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60808060405234601557610264908161001b8239f35b600080fdfe608080604052600436101561008d575b5036156100525760405162461bcd60e51b815260206004820152601460248201527311985b1b189858dac81b9bdd08185b1b1bddd95960621b6044820152606490fd5b60405162461bcd60e51b8152602060048201526013602482015272149958d95a5d99481b9bdd08185b1b1bddd959606a1b6044820152606490fd5b60003560e01c6336d306a40361000f5760e0366003190112610229576004356001600160a01b03811691908290036102295760243560ff8116809103610229576044359067ffffffffffffffff821680920361022957606435936004851015610229576084359267ffffffffffffffff8411610229573660238501121561022957836004013567ffffffffffffffff81116102295736602482870101116102295760a4359360c43595868601928387116102135760209789978260248a9895899660e4986334f23a9d60e01b895260048901528288015260009e604488015260c060648801528260c4880152018686013783830185018c9052608484015260a4830152601f01601f191681010301925af18015610208576101ac575080f35b906020913d602011610200575b601f8301601f191681019267ffffffffffffffff8411828510176101ec5760209293604052810103126101e95780f35b80fd5b634e487b7160e01b83526041600452602483fd5b3d92506101b9565b6040513d84823e3d90fd5b634e487b7160e01b600052601160045260246000fd5b600080fdfea2646970667358221220dd50fb15432bdeb4a5c898a8a68ac87c93ee52812421475097443f1dfb6f6ecb64736f6c634300081c0033";

type FallbackFailureConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FallbackFailureConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FallbackFailure__factory extends ContractFactory {
  constructor(...args: FallbackFailureConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FallbackFailure & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): FallbackFailure__factory {
    return super.connect(runner) as FallbackFailure__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FallbackFailureInterface {
    return new Interface(_abi) as FallbackFailureInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FallbackFailure {
    return new Contract(address, _abi, runner) as unknown as FallbackFailure;
  }
}
