/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FallbackFailureInterface extends Interface {
  getFunction(
    nameOrSignature: "insertRequestOnProcessorEndpoint"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "insertRequestOnProcessorEndpoint",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "insertRequestOnProcessorEndpoint",
    data: BytesLike
  ): Result;
}

export interface FallbackFailure extends BaseContract {
  connect(runner?: ContractRunner | null): FallbackFailure;
  waitForDeployment(): Promise<this>;

  interface: FallbackFailureInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  insertRequestOnProcessorEndpoint: TypedContractMethod<
    [
      processorEndpoint: AddressLike,
      protocolVersion: BigNumberish,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      tokenAddress: AddressLike,
      assetAmount: BigNumberish,
      maxFeeValue: BigNumberish
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "insertRequestOnProcessorEndpoint"
  ): TypedContractMethod<
    [
      processorEndpoint: AddressLike,
      protocolVersion: BigNumberish,
      applicationId: BigNumberish,
      requestType: BigNumberish,
      payload: BytesLike,
      tokenAddress: AddressLike,
      assetAmount: BigNumberish,
      maxFeeValue: BigNumberish
    ],
    [void],
    "payable"
  >;

  filters: {};
}
