/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Structs {
  export type EventDataStruct = { events: BytesLike[]; subTypes: BytesLike[] };

  export type EventDataStructOutput = [events: string[], subTypes: string[]] & {
    events: string[];
    subTypes: string[];
  };

  export type TokenAndAmountStruct = {
    token: AddressLike;
    amount: BigNumberish;
  };

  export type TokenAndAmountStructOutput = [token: string, amount: bigint] & {
    token: string;
    amount: bigint;
  };
}

export interface TestTriggerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "capturedBalances"
      | "execute"
      | "executedInBlock"
      | "executedPostWithdrawsInBlock"
      | "getTrustProcessPayload"
      | "processorEndpoint"
      | "revertOnExecute"
      | "revertOnPostWithdraw"
      | "setTrustedPayload"
      | "tokenAllowlist"
      | "trustedPayload"
      | "withdraw"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TriggerExecuted"): EventFragment;

  encodeFunctionData(
    functionFragment: "capturedBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [Structs.EventDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "executedInBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executedPostWithdrawsInBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrustProcessPayload",
    values: [
      Structs.EventDataStruct,
      boolean,
      boolean,
      Structs.TokenAndAmountStruct[],
      Structs.TokenAndAmountStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "processorEndpoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertOnExecute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertOnPostWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedPayload",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenAllowlist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trustedPayload",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "capturedBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executedInBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executedPostWithdrawsInBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustProcessPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processorEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertOnExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertOnPostWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenAllowlist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace TriggerExecutedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TestTrigger extends BaseContract {
  connect(runner?: ContractRunner | null): TestTrigger;
  waitForDeployment(): Promise<this>;

  interface: TestTriggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  capturedBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  execute: TypedContractMethod<
    [appEventData: Structs.EventDataStruct],
    [void],
    "nonpayable"
  >;

  executedInBlock: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  executedPostWithdrawsInBlock: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  getTrustProcessPayload: TypedContractMethod<
    [
      appEventData: Structs.EventDataStruct,
      executeSuccess: boolean,
      withdrawSuccess: boolean,
      returnedTokens: Structs.TokenAndAmountStruct[],
      failedTokens: Structs.TokenAndAmountStruct[]
    ],
    [string],
    "nonpayable"
  >;

  processorEndpoint: TypedContractMethod<[], [string], "view">;

  revertOnExecute: TypedContractMethod<[], [boolean], "view">;

  revertOnPostWithdraw: TypedContractMethod<[], [boolean], "view">;

  setTrustedPayload: TypedContractMethod<
    [payload: BytesLike],
    [void],
    "nonpayable"
  >;

  tokenAllowlist: TypedContractMethod<[], [string], "view">;

  trustedPayload: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<
    [],
    [
      [
        Structs.TokenAndAmountStructOutput[],
        Structs.TokenAndAmountStructOutput[]
      ]
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "capturedBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [appEventData: Structs.EventDataStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executedInBlock"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "executedPostWithdrawsInBlock"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getTrustProcessPayload"
  ): TypedContractMethod<
    [
      appEventData: Structs.EventDataStruct,
      executeSuccess: boolean,
      withdrawSuccess: boolean,
      returnedTokens: Structs.TokenAndAmountStruct[],
      failedTokens: Structs.TokenAndAmountStruct[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processorEndpoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revertOnExecute"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "revertOnPostWithdraw"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setTrustedPayload"
  ): TypedContractMethod<[payload: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenAllowlist"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "trustedPayload"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [],
    [
      [
        Structs.TokenAndAmountStructOutput[],
        Structs.TokenAndAmountStructOutput[]
      ]
    ],
    "nonpayable"
  >;

  getEvent(
    key: "TriggerExecuted"
  ): TypedContractEvent<
    TriggerExecutedEvent.InputTuple,
    TriggerExecutedEvent.OutputTuple,
    TriggerExecutedEvent.OutputObject
  >;

  filters: {
    "TriggerExecuted()": TypedContractEvent<
      TriggerExecutedEvent.InputTuple,
      TriggerExecutedEvent.OutputTuple,
      TriggerExecutedEvent.OutputObject
    >;
    TriggerExecuted: TypedContractEvent<
      TriggerExecutedEvent.InputTuple,
      TriggerExecutedEvent.OutputTuple,
      TriggerExecutedEvent.OutputObject
    >;
  };
}
